// Copyright 2024 TII (SSRC) and the Ghaf contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.2
// source: socket.proto

package socketproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SocketStream_Sync_FullMethodName        = "/socketproxy.SocketStream/Sync"
	SocketStream_ReceiveData_FullMethodName = "/socketproxy.SocketStream/ReceiveData"
)

// SocketStreamClient is the client API for SocketStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocketStreamClient interface {
	Sync(ctx context.Context, in *SyncData, opts ...grpc.CallOption) (*SyncData, error)
	ReceiveData(ctx context.Context, opts ...grpc.CallOption) (SocketStream_ReceiveDataClient, error)
}

type socketStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewSocketStreamClient(cc grpc.ClientConnInterface) SocketStreamClient {
	return &socketStreamClient{cc}
}

func (c *socketStreamClient) Sync(ctx context.Context, in *SyncData, opts ...grpc.CallOption) (*SyncData, error) {
	out := new(SyncData)
	err := c.cc.Invoke(ctx, SocketStream_Sync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socketStreamClient) ReceiveData(ctx context.Context, opts ...grpc.CallOption) (SocketStream_ReceiveDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &SocketStream_ServiceDesc.Streams[0], SocketStream_ReceiveData_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &socketStreamReceiveDataClient{stream}
	return x, nil
}

type SocketStream_ReceiveDataClient interface {
	Send(*SocketDataStream) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type socketStreamReceiveDataClient struct {
	grpc.ClientStream
}

func (x *socketStreamReceiveDataClient) Send(m *SocketDataStream) error {
	return x.ClientStream.SendMsg(m)
}

func (x *socketStreamReceiveDataClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SocketStreamServer is the server API for SocketStream service.
// All implementations must embed UnimplementedSocketStreamServer
// for forward compatibility
type SocketStreamServer interface {
	Sync(context.Context, *SyncData) (*SyncData, error)
	ReceiveData(SocketStream_ReceiveDataServer) error
	mustEmbedUnimplementedSocketStreamServer()
}

// UnimplementedSocketStreamServer must be embedded to have forward compatible implementations.
type UnimplementedSocketStreamServer struct {
}

func (UnimplementedSocketStreamServer) Sync(context.Context, *SyncData) (*SyncData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedSocketStreamServer) ReceiveData(SocketStream_ReceiveDataServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveData not implemented")
}
func (UnimplementedSocketStreamServer) mustEmbedUnimplementedSocketStreamServer() {}

// UnsafeSocketStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocketStreamServer will
// result in compilation errors.
type UnsafeSocketStreamServer interface {
	mustEmbedUnimplementedSocketStreamServer()
}

func RegisterSocketStreamServer(s grpc.ServiceRegistrar, srv SocketStreamServer) {
	s.RegisterService(&SocketStream_ServiceDesc, srv)
}

func _SocketStream_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocketStreamServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocketStream_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocketStreamServer).Sync(ctx, req.(*SyncData))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocketStream_ReceiveData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SocketStreamServer).ReceiveData(&socketStreamReceiveDataServer{stream})
}

type SocketStream_ReceiveDataServer interface {
	SendAndClose(*Empty) error
	Recv() (*SocketDataStream, error)
	grpc.ServerStream
}

type socketStreamReceiveDataServer struct {
	grpc.ServerStream
}

func (x *socketStreamReceiveDataServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *socketStreamReceiveDataServer) Recv() (*SocketDataStream, error) {
	m := new(SocketDataStream)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SocketStream_ServiceDesc is the grpc.ServiceDesc for SocketStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocketStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "socketproxy.SocketStream",
	HandlerType: (*SocketStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _SocketStream_Sync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveData",
			Handler:       _SocketStream_ReceiveData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "socket.proto",
}
