name: Amend Dependabot Go PRs

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'go.mod'
      - 'go.sum'

jobs:
  amend:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Go Setup
        uses: actions/setup-go@v5.4.0
        with:
          go-version: '>=1.24'

      - name: Go Version
        run: go version

      - name: Install nix
        uses: cachix/install-nix-action@526118121621777ccd86f79b04685a9319637641 # v31.3.0

      - name: Replace go vendor hash
        run: |
          go mod tidy
          go mod vendor
          VENDOR_HASH=$(nix hash path --base64 --type sha256 vendor/)
          rm -r vendor/
          sed -i -E 's|^([[:space:]]*vendorHash = "sha256-)[^"]*(";$)|\1'"$VENDOR_HASH"'\2|' nixos/packages/givc-agent.nix

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.email "<49699333+dependabot[bot]@users.noreply.github.com>"
          git config user.name "dependabot[bot]"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add nixos/packages/givc-agent.nix
          git commit -m "chore(deps): update vendorHash for updated Go dependencies"
          git push origin HEAD:${{ github.head_ref }}
