name: Amend Dependabot Go PRs

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'go.mod'
      - 'go.sum'

jobs:
  amend:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: true
          fetch-depth: 0

      - name: Go Setup
        uses: actions/setup-go@v5.4.0
        with:
          go-version: '>=1.24'

      - name: Go Version
        run: go version

      - name: Replace go vendor hash
        run: |
          go mod tidy
          go mod vendor
          VENDOR_HASH=$(nix hash path --base64 --type sha256 vendor/)
          rm -r vendor/
          sed -i -E 's|^([[:space:]]*vendorHash = "sha256-)[^"]*(";$)|\1'"$VENDOR_HASH"'\2|' nixos/packages/givc-agent.nix

      - name: Commit & push changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add nixos/packages/givc-agent.nix
          git commit -m "chore(deps): update vendorHash for updated Go dependencies"
          git push origin HEAD:${{ github.head_ref }}
