# SPDX-FileCopyrightText: 2022-2024 TII (SSRC) and the Ghaf contributors
# SPDX-License-Identifier: Apache-2.0

name: go-sectest
on:
    push:
        paths:
        - 'modules/**'
    pull_request:
        paths:
        - 'modules/**'
permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout Source
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install libudev-dev (for go-udev)
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: Run Gosec Security Scanner
        uses: securego/gosec@15d5c61e866bc2e2e8389376a31f1e5e09bde7d8 # master
        with:
          args: '-exclude=G302,G204 -no-fail ./modules/...'
      - name: Run Go Tests
        run: go test -v ./modules/...
